### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by JustFrederik** [JustFrederik/cargo-toml-language-server#1]
- [ ] UI
  - [ ] crate Info UI
    - [ ] crate dependencies
    - [ ] categories, tags, name ...
  - [ ] Features UI
- [ ] Code Actions
  - [ ] goto repo
  - [ ] goto docs.rs
  - [ ] update & upgrade
  - [ ] update & upgrade all
- [ ] Inlay hints for dependencies(display version that will be used 0.4 => 0.4.5 & display what it will update to 0.8 => 0.8.5)
- [ ] Version suggestion
- [ ] Feature suggestion
- [ ] faster dependency suggestion
